package com.shop.mapper;

import com.shop.dto.CartDto;
import com.shop.entity.Cart;
import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

/**
 * This interface defines mapping between Cart and CartDto objects in a shopping application.
 */
@Mapper
public interface CartMapper {

    /**
     * Instance of the CartMapper generated by MapStruct.
     */
    CartMapper INSTANCE = Mappers.getMapper(CartMapper.class);

    /**
     * Maps a Cart entity to a CartDto.
     *
     * @param entity The Cart entity to map.
     * @return The mapped CartDto.
     */
    CartDto mapToDto(Cart entity);
}
